name: Push & PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RSPEC: '${{ matrix.rspec }}'
    strategy:
      fail-fast: false
      matrix:
        rspec: ['3.0', '3.12']
        ruby: ['3.0', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true
        cache-version: '${{ matrix.rspec }}'
    - name: Rspec
      run: bundle exec rspec
    - name: Cucumber
      run: bundle exec cucumber --quiet --tags 'not @fail'
    - name: Cucumber (expected to fail)
      run: bundle exec cucumber --quiet --tags '@fail' --wip
